const { mountURL } = require('./config-mapping');

const ACCOUNT_ROOT_URL = `${mountURL}account`;
const ACCOUNT_CONTEXT_PATH = '/account';
const GRANT_ROOT_URL = `${mountURL}grant`;
const GRANT_CONTEXT_PATH = '/grant';
const BASE_ROOT_URL = `${mountURL}`;
const CLAIM_ROOT_URL = `${mountURL}claim`;
const CLAIM_CONTEXT_PATH = '/claim';
const SUPPORT_WORKER_ROOT_URL = `${mountURL}support-worker`;
const SUPPORT_WORKER_CONTEXT_PATH = '/support-worker';
const EQUIPMENT_OR_ADAPTATION_ROOT_URL = `${mountURL}specialist-equipment`;
const EQUIPMENT_OR_ADAPTATION_CONTEXT_PATH = '/specialist-equipment';
const TRAVEL_TO_WORK_ROOT_URL = `${mountURL}travel-to-work`;
const TRAVEL_TO_WORK_CONTEXT_PATH = '/travel-to-work';
const WORKPLACE_CONTACT_URL = `${mountURL}amend-workplace-contact`;
const WORKPLACE_CONTACT_CONTEXT_PATH = '/amend-workplace-contact';
const PERSONAL_INFORMATION_CONTEXT_PATH = '/personal';
const PERSONAL_INFORMATION_URL = `${mountURL}personal`;
const PUBLIC_URL = `${mountURL}public`;
const PUBLIC_CONTEXT_PATH = '/public';

const authenticatedRoutes = [
  ACCOUNT_ROOT_URL,
  ACCOUNT_CONTEXT_PATH,
  GRANT_ROOT_URL,
  GRANT_CONTEXT_PATH,
  BASE_ROOT_URL,
  CLAIM_CONTEXT_PATH,
  CLAIM_ROOT_URL,
  SUPPORT_WORKER_ROOT_URL,
  SUPPORT_WORKER_CONTEXT_PATH,
  EQUIPMENT_OR_ADAPTATION_ROOT_URL,
  EQUIPMENT_OR_ADAPTATION_CONTEXT_PATH,
  TRAVEL_TO_WORK_ROOT_URL,
  TRAVEL_TO_WORK_CONTEXT_PATH,
  WORKPLACE_CONTACT_URL,
  WORKPLACE_CONTACT_CONTEXT_PATH,
  PERSONAL_INFORMATION_URL,
  PERSONAL_INFORMATION_CONTEXT_PATH,
];

module.exports = {
  ACCOUNT_ROOT_URL,
  ACCOUNT_CONTEXT_PATH,
  GRANT_ROOT_URL,
  GRANT_CONTEXT_PATH,
  BASE_ROOT_URL,
  CLAIM_ROOT_URL,
  CLAIM_CONTEXT_PATH,
  SUPPORT_WORKER_ROOT_URL,
  SUPPORT_WORKER_CONTEXT_PATH,
  EQUIPMENT_OR_ADAPTATION_ROOT_URL,
  EQUIPMENT_OR_ADAPTATION_CONTEXT_PATH,
  TRAVEL_TO_WORK_ROOT_URL,
  TRAVEL_TO_WORK_CONTEXT_PATH,
  WORKPLACE_CONTACT_URL,
  WORKPLACE_CONTACT_CONTEXT_PATH,
  PERSONAL_INFORMATION_URL,
  PERSONAL_INFORMATION_CONTEXT_PATH,
  PUBLIC_URL,
  PUBLIC_CONTEXT_PATH,
  authenticatedRoutes,
};
